QASM reals, readme updates, minor changes

diff --git a/qunity-compile b/qunity-compile
--- a/qunity-compile
+++ b/qunity-compile
@@ -50,6 +50,9 @@ elif [ $status -eq 0 ]; then
 
     if $analyze; then
         python3 qasm_analyze.py $out_filename
+        if [ $? -ne 0 ]; then
+            echo -e "${RED}Analysis script error${NC}"
+        fi
     fi
 else
     echo -e "${RED}Compiler error${NC}"
